flows:
  - 'flows/onboarding/*'
  - 'flows/swap/*'
  - 'flows/restore/*'
  - 'flows/deeplinks/*'
  - 'flows/explore/*'
  - 'flows/portfolio/*'
baselineBranch: main
executionOrder:
  continueOnFailure: true
