name: "Tag and release"
on:
  push:
    branches:
      - 'main'
permissions:
  contents: write
  issues: write
  pull-requests: write
jobs:
  deploy-to-prod:
    runs-on: ubuntu-latest
    steps:
      - uses: bullfrogsec/bullfrog@dcde5841b19b7ef693224207a7fdec67fce604db # v0.8.3
        with:
          # List of IPs to allow outbound connections to.
          # By default, only localhost and IPs required for the essential operations of Github Actions are allowed.
          # allowed-ips:|
      
          # List of domains to allow outbound connections to.
          # Wildcards are accepted. For example, if allowing `*.google.com`, this will allow `www.google.com`, `console.cloud.google.com` but not `google.com`.
          # By default, only domains required for essential operations of Github Actions and uploading job summaries are allowed.
          # Refer to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#communication-requirements-for-github-hosted-runners-and-github for additional domains that should be allowed for additional Github Actions features.
          #allowed-domains: |
          # The egress policy to enforce. Valid values are `audit` and `block`.
          # Default: audit
          egress-policy: audit
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: 🧷️ Get version
        uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b
        id: version
        with:
          path: VERSION

      - name: 🧾️ Get release notes
        uses: juliangruber/read-file-action@02bbba9876a8f870efd4ad64e3b9088d3fb94d4b
        id: release-notes
        with:
          path: RELEASE

      - name: 🏷️ Tag
        id: github-tag-action
        uses: uniswap/github-tag-action@7bddacd4864a0f5671e836721db60174d8a9c399
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.version.outputs.content }}
          tag_prefix: ""

      - name: 🪽 Create release
      
        on:
          push:
          tags:
            - v*

          permissions:
          contents: write

      jobs:
          release:
          name: Release pushed tag
          runs-on: ubuntu-24.04
          steps:
            - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
